import pytest
from unittest.mock import MagicMock, patch
import os
import json
from pathlib import Path
from src.genai_client import GeminiClient
from config import GEMINI_CACHE_PATH

@pytest.fixture(autouse=True)
def clean_cache():
    # Rimuove il file di cache prima di ogni test per isolare le esecuzioni
    if os.path.exists(GEMINI_CACHE_PATH):
        try:
            os.remove(GEMINI_CACHE_PATH)
        except Exception:
            pass
    yield
    if os.path.exists(GEMINI_CACHE_PATH):
        try:
            os.remove(GEMINI_CACHE_PATH)
        except Exception:
            pass

def test_genai_client_fallback_without_key():
    # Senza chiave, deve usare il fallback automatico
    with patch.dict(os.environ, {}, clear=True):
        client = GeminiClient()
        assert client.client is None
        
        reviews = client.generate_reviews("PROD_123", 2, "positive")
        assert len(reviews) == 2
        assert "PROD_123" in reviews[0]["text"]
        assert "PROD_123" in reviews[1]["text"]
        assert reviews[0]["title"] == "Excellent product! 0"

def test_genai_client_with_key_and_mock_api():
    # Simula la risposta di Gemini
    mock_response = MagicMock()
    mock_response.text = json.dumps([
        {"title": "Gemini review 1", "text": "Text 1 generated by Gemini model."},
        {"title": "Gemini review 2", "text": "Text 2 generated by Gemini model."},
        {"title": "Gemini review 3", "text": "Text 3 generated by Gemini model."},
        {"title": "Gemini review 4", "text": "Text 4 generated by Gemini model."},
        {"title": "Gemini review 5", "text": "Text 5 generated by Gemini model."}
    ])
    
    with patch("google.genai.Client") as mock_client_class:
        mock_client = MagicMock()
        mock_client.models.generate_content.return_value = mock_response
        mock_client_class.return_value = mock_client
        
        with patch.dict(os.environ, {"GEMINI_API_KEY": "fake_key"}):
            client = GeminiClient()
            client.client = mock_client
            
            # Richiediamo 2 recensioni
            reviews = client.generate_reviews("PROD_ABC", 2, "positive")
            assert len(reviews) == 2
            assert reviews[0]["title"] == "Gemini review 1"
            
            # Verifichiamo che il client abbia generato un batch di 5 (pre-caching)
            mock_client.models.generate_content.assert_called_once()
            assert f"PROD_ABC_positive" in client.cache
            assert len(client.cache["PROD_ABC_positive"]) == 5
            
            # Seconda chiamata per lo stesso prodotto/sentiment: deve usare la cache e non chiamare l'API
            mock_client.models.generate_content.reset_mock()
            reviews_cached = client.generate_reviews("PROD_ABC", 3, "positive")
            assert len(reviews_cached) == 3
            assert reviews_cached[2]["title"] == "Gemini review 3"
            mock_client.models.generate_content.assert_not_called()
